apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      web: flipkart
  template:
    metadata:
      labels:
        web: flipkart
    spec:
      containers:
      - name: flip-count
        image: muralisocial123/flipkart-clone-kuberox:v1.1.0
        ports:
        - containerPort: 80
