apiVersion: apps/v1
kind: Deployment
metadata:
  name: fck
spec:
  replicas: 5
  selector:
    matchLabels:
      web: fc
  template:
    metadata:
      labels: 
        web: fc
    spec:
      containers:
      - name: fck
        image: muralisocial123/flipkart-clone-kuberox:v1.1.0
        ports:
        - containerPort: 4545
