apiVersion: apps/v1
kind: Deployment
metadata:
  name: flipkart-transaction
spec:
  replicas: 5
  selector:
    matchLabels:
      web: flip
  template:
    metadata:
      labels: 
        web: flip
    spec:
      containers:
      - name: flipkart
        image: muralisocial123/muralisocial123/transaction-app:v1.0.0
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: flipkart-transaction
spec:
  selector:
    web: flip
  ports:
  -  protocol: TCP
     port: 8081     # Service port / Host Port
     targetPort: 8080   # target port - container port 
